name: electric-mobx-example

services:
  pg:
    image: postgres:17-alpine
    restart: unless-stopped
    shm_size: 1g
    ports:
      - "5442:5432"
    environment:
      POSTGRES_USER: electric_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: electric
    volumes:
      - pg:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: |
      postgres
      -c wal_level=logical
      -c max_wal_senders=10
      -c max_replication_slots=5
      -c hot_standby=on
      -c hot_standby_feedback=on

  electric:
    image: electricsql/electric:1.0.0-beta.15
    environment:
      DATABASE_URL: postgresql://electric_user:password@pg:5432/electric?sslmode=disable
    ports:
      - "4027:3000"
    depends_on:
      - pg
    networks:
      - internal

volumes:
  pg:

networks:
  internal:
